
GET http://localhost:3003/users
content-type: application/json

###

POST http://localhost:3003/users
content-type: application/json

{
    "name": "Bianca Paccola",
    "email": "bianca@email.com",
    "password": "123456",
    "passwordConfirm" : "123456"
}

###

POST http://localhost:3003/products
content-type: application/json

{
    "name": "Livro: Diário de um Mago",
    "price": 29.90,
    "image" : "https://m.media-amazon.com/images/I/517S5CSFX1L._SX331_BO1,204,203,200_.jpg"
}

###

GET http://localhost:3003/products?order=asc&&search=pente
content-type: application/json

###

POST http://localhost:3003/purchases
content-type: application/json

{
    "userId": "1670179225442", 
    "productId": "1670185428204", 
    "quantity": 2
}

###

GET http://localhost:3003/users/1670179379130/purchases
content-type: application/json